# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    echo "---"
    cmd /C "find 'C:/' -name winsock2.h"
    set
  displayName: 'printenv'
  
- script: |
    #set PATH=C:/Strawberry/perl/bin;C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin;%PATH%
    set INCLUDE=C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/SDK/ScopeCppSDK/VC/include/;C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/SDK/ScopeCppSDK/SDK/include/ucrt/;C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/SDK/ScopeCppSDK/SDK/include/
    set PATH=C:/Strawberry/perl/bin;C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/SDK/ScopeCppSDK/VC/bin/;%PATH%
    git clone https://github.com/openssl/openssl.git -b OpenSSL_1_1_1b
    cd openssl
    echo *** configure **
    perl.exe Configure VC-WIN32 no-asm
    echo *** make **
    nmake.exe
    echo *** make install **
    nmake.exe install
  displayName: 'install openssl'
    
- script: |
    ls C:\
    echo "---"
    DIR "C:\Build_OpenSSL_VC_32"
    echo "---"
    set
  displayName: 'explore tree'

- script: |	
    mkdir build	
    cd build	
    cmake ..	
    cmake --build . --config Release
  displayName: 'cmake test'
