# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

strategy:
  matrix:
    p1:
       VAL1: "A"
       VAL2: "B"
    p2:
       VAL1: "C"
       VAL2: "D"

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    echo VAL1
    echo VAL2
    echo %VAL1%
    echo %VAL2%
  displayName: 'print matrix'


- script: |
    echo "---"
    DIR "C:\Program Files (x86)"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include"
    echo "---"
    set
  displayName: 'printenv'

- script: |	
    mkdir build	
    cd build	
    cmake ..	
    cmake --build . --config Release
  displayName: 'cmake test'
