# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job:
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      DIR "C:\Program Files\OpenSSL\"
      set VAL1="111"
      set VAL2="222"
      echo %VAL1%
      echo %VAL2%
    displayName: 'print matrix1'

- job:
  strategy:
    matrix:
      p1:
         VAL1: "A"
         VAL2: "B"
      p2:
         VAL1: "C"
         VAL2: "D"
  steps:
  - script: |
      echo %VAL1%
      echo %VAL2%
    displayName: 'print matrix2'
  - script: |	
      mkdir build	
      cd build	
      cmake ..	
      cmake --build . --config Release
    displayName: 'cmake test'
