# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    echo "---"
    DIR "C:\Program Files (x86)"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023"
    echo "---"
    DIR "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include"
    echo "---"
    set
  displayName: 'printenv'
  
- script: |
    #set PATH=C:/Strawberry/perl/bin;C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin;%PATH%
    set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt\winrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include
    set LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\um\x64;C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\lib\x64\store;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.17763.0\ucrt\x64
    set PATH=C:\Program Files (x86)\Windows Kits\10\bin\10.0.17763.0\x64;C:/Strawberry/c/x86_64-w64-mingw32/bin;C:/Strawberry/perl/bin;C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/SDK/ScopeCppSDK/VC/bin/;%PATH%
    git clone https://github.com/openssl/openssl.git -b OpenSSL_1_1_1b
    cd openssl
    echo *** configure **
    perl.exe Configure VC-WIN64A no-asm
    #perl Configure --prefix=$PWD/dist no-idea no-mdc2 no-rc5 shared mingw64
    echo *** make depend**
    nmake depend
    echo *** make **
    nmake
    echo *** make install **
    nmake install
  displayName: 'install openssl'
    
- script: |
    ls C:\
    echo "---"
    DIR "C:\Build_OpenSSL_VC_32"
    echo "---"
    set
  displayName: 'explore tree'

- script: |	
    mkdir build	
    cd build	
    cmake ..	
    cmake --build . --config Release
  displayName: 'cmake test'
