# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    mkdir tmp
    bitsadmin.exe /TRANSFER htmlget https://www.openssl.org/source/openssl-1.1.1b.tar.gz tmp
    tar xzf openssl-1.1.1b.tar.gz
    cd openssl-1.1.1b
    make
    make install
  displayName: 'install openssl'
    
- script: |
    ls C:\
    echo "---"
    DIR "C:\Program Files\OpenSSL"
    echo "---"
    set
  displayName: 'explore tree'

- script: |
    mkdir build
    cd build
    cmake ..
    cmake --build . --config Release
  displayName: 'cmake test'
