# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    DIR "C:\Program Files\"
    echo "---"
    DIR "C:\Program Files(x86)\"
    echo "---"
    find C:\Program Files\ -name perl.exe
    echo "---"
    find C:\Program Files(x86)\ -name perl.exe
    echo "---"
    set
  displayName: 'printenv'
  
- script: |
    git clone https://github.com/openssl/openssl.git -b OpenSSL_1_1_1b
    cd openssl
    echo *** configure **
    perl Configure VC-WIN32 no-asm
    echo *** make **
    make
    echo *** make install **
    make install
  displayName: 'install openssl'
    
- script: |
    ls C:\
    echo "---"
    DIR "C:\Build_OpenSSL_VC_32"
    echo "---"
    set
  displayName: 'explore tree'

- script: |	
    mkdir build	
    cd build	
    cmake ..	
    cmake --build . --config Release
  displayName: 'cmake test'
