# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: tree C:\Program Files\Boost\1.69.0\
  displayName: 'explore tree'

- script: |
    mkdir build
    cd build
    cmake ..
    cmake --build . --config Release
  displayName: 'cmake test'
