# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    ls C:\
    echo "---"
    ls "C:\Program Files\Boost\1.69.0\libs"
    echo "---"
    ls "C:\Program Files\Boost\1.69.0\lib"
    echo "---"
    set
    echo "---"
    ls %BOOST_ROOT%
    echo "---"
  displayName: 'explore tree'

- script: |
    mkdir build
    cd build
    cmake ..
    cmake --build . --config Release
  displayName: 'cmake test'
